### ISSUE TITLE
Button color not displaying properly on page 

### ISSUE THREAD

**Issue by AndyLarre77** [Shelob9/ingot#179] opened 2016-01-14 20:15 UTC
Testing Ingot v1.0.2 on testing site Foundri.net, PHP 5.6, WordPress 4.4.1, Theme twenty sixteen. 
Problem persists with all plugins deactivated. 
![screen shot 2016-01-14 at 3 14 34 pm](https://cloud.githubusercontent.com/assets/14261015/12336247/9162a66a-bad1-11e5-9b44-81c357f83866.png)

**Comment by Shelob9** [comment] 2016-01-14 22:50
This wasn't fixed in 1.0.2. It is fixed in 1.1.0

**Comment by Shelob9** [comment] 2016-01-15 00:30
Dupe of #161

**Closed as completed** 2016-01-15 00:29 UTC
Labels: invalid
